name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Android Continuous Integration

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: set up JDK 17
      uses: actions/setup-java@v2.3.1
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Setup key file
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ github.workspace }}/keystore.jks
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}

    - name: List files in workspace
      run: ls -l

    - name: Build and Sign release variant
      run: |
        ./gradlew assembleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Test with Gradle
      run: ./gradlew test
      
    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat version.properties | grep 'version_name' | cut -d'=' -f2)" >> $GITHUB_ENV

    - name: Get Latest Release Tag
      id: latest_release
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
        echo "Latest release tag is $LATEST_TAG"
    
    - name: Check if Current Version is Greater than Latest Release
      id: check_version
      run: |
        if [ "$VERSION" \> "$LATEST_TAG" ]; then
          echo "Current version ($VERSION) is greater than latest release ($LATEST_TAG)"
          echo "CREATE_RELEASE=true" >> $GITHUB_ENV
        else
          echo "Current version ($VERSION) is not greater than latest release ($LATEST_TAG)"
          echo "CREATE_RELEASE=false" >> $GITHUB_ENV
        fi

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && env.CREATE_RELEASE == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
      
    - name: Upload Release Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && env.CREATE_RELEASE == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/expenseTracker.apk
        asset_name: expenseTracker-${{ env.VERSION }}.apk
        asset_content_type: application/vnd.android.package-archive
    